name: Build Android APK (from ZIP)

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '8.5'

      - name: Unzip Android project
        run: |
          sudo apt-get update && sudo apt-get install -y unzip
          unzip -o PisYedili_Android_Menu.zip

      - name: Build debug APK
        working-directory: PisYedili_Android_Menu
        run: |
          gradle :app:assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: pisyedili-debug-apk
          path: PisYedili_Android_Menu/app/build/outputs/apk/debug/*.apk
